# Generated by Django 4.2.3 on 2023-08-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curiosidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('CATEGORIA', 'categoria'), ('CAT', 'cat')], default='CATEGORIA', max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='imagem/%Y/%m/%d/')),
                ('publicada', models.BooleanField(default=False)),
            ],
        ),
    ]
