# Generated by Django 4.2.3 on 2023-07-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidamarinha', '0002_rename_imagem_curiosidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curiosidade',
            old_name='descrisao',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='curiosidade',
            name='data',
        ),
        migrations.AlterField(
            model_name='curiosidade',
            name='categoria',
            field=models.CharField(choices=[('CATEGORIA', 'categoria'), ('CAT', 'cat')], default='CATEGORIA', max_length=100),
        ),
        migrations.AlterField(
            model_name='curiosidade',
            name='foto',
            field=models.ImageField(blank=True, upload_to='imagem/%Y/%m/%d/'),
        ),
    ]
