# Generated by Django 4.2.3 on 2023-07-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesca', '0002_rename_imagem_pesca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesca',
            name='categoria',
            field=models.CharField(choices=[('CATEGORIA', 'categoria'), ('CAT', 'cat')], default='', max_length=100),
        ),
    ]
