# Generated by Django 4.2.3 on 2023-07-20 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('descrisao', models.TextField()),
                ('foto', models.ImageField(upload_to='imagem/%Y/%m/%d/')),
                ('publicada', models.BooleanField(default=False)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
