# Generated by Django 4.2.3 on 2023-08-02 01:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=125)),
                ('legenda', models.CharField(max_length=125)),
                ('categoria', models.CharField(choices=[('PESSOA', 'pessoa'), ('CONSOLE', 'console')], default='OPCOES_CATEGORIA', max_length=125)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='imagem/%Y/%n/%d/')),
                ('eh_publicada', models.BooleanField(default=False)),
                ('data_fotografia', models.DateTimeField(default=datetime.datetime.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descricao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
