# Generated by Django 4.2.3 on 2023-08-01 14:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=125)),
                ('email', models.EmailField(max_length=125)),
                ('senha', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=125)),
                ('legenda', models.CharField(max_length=125)),
                ('categoria', models.CharField(choices=[('PESSOA', 'pessoa'), ('CONSOLE', 'console')], default='OPCOES_CATEGORIA', max_length=125)),
                ('descrisao', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='imagem/%Y/%n/%d/')),
                ('eh_publicada', models.BooleanField(default=False)),
                ('data_fotografia', models.DateTimeField(default=datetime.datetime.now)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.cadastro')),
            ],
        ),
    ]
