# Generated by Django 4.2.3 on 2023-08-03 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='other_field1',
            field=models.CharField(default='OPCAO_USUARIO', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='other_field2',
            field=models.CharField(default='OPCAO_USUARIO', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
