# Generated by Django 4.2.3 on 2023-08-03 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0002_imagem_usuario_other_field1_usuario_other_field2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(choices=[('PESSOA', 'pessoa'), ('CONSOLE', 'console')], default='PESSOA', max_length=125),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='other_field1',
            field=models.CharField(default='USUARIO', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='other_field2',
            field=models.CharField(default='USUARIO', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
